name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.6.2
  EXPORT_NAME: test-project
  PROJECT_PATH: test-project

jobs:
  export-linux:
    name: Linux Export
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.6.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux" ../build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: https://gitea.com/actions/gitea-upload-artifact@v4
        with:
          name: linux
          path: build/linux
